/* The following code was generated by JFlex 1.4.3 on 28/08/18 14:53 */

package MiniC;
import static minic.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/08/18 14:53 from the specification file
 * <tt>C:/Users/TonyTaze/Downloads/Universidad/Sexto Ciclo/COMPILADORES/analizadorLexico-Java/src/analizador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\35\1\34\2\0\1\33\22\0\1\36\1\44\1\56\2\0"+
    "\1\37\1\46\1\0\1\52\1\53\1\41\1\42\1\37\1\42\1\43"+
    "\1\40\1\63\11\61\1\0\1\37\1\44\1\45\1\44\2\0\4\65"+
    "\1\6\1\65\6\60\1\32\1\31\11\60\1\66\2\60\1\50\1\0"+
    "\1\51\1\0\1\57\1\0\1\1\1\2\1\3\1\4\1\5\1\7"+
    "\1\10\1\11\1\12\1\60\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\60\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\60"+
    "\1\54\1\47\1\55\u1f9e\0\1\62\1\64\udfe2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\16\2\1\3\1\4\1\5\1\6\10\7"+
    "\1\10\1\1\1\11\1\1\11\2\1\12\12\2\1\13"+
    "\1\14\1\10\1\15\2\0\1\1\1\16\1\1\1\0"+
    "\1\2\1\1\10\2\1\12\6\2\1\12\2\1\2\0"+
    "\6\2\1\17\1\2\1\0\1\16\1\0\1\1\6\2"+
    "\1\11\3\2\1\1\4\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339"+
    "\0\u0370\0\u03a7\0\u03de\0\67\0\67\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b"+
    "\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3"+
    "\0\u082a\0\156\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974"+
    "\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\67\0\67"+
    "\0\u05cd\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f"+
    "\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf"+
    "\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167"+
    "\0\u119e\0\u11d5\0\156\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8"+
    "\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432\0\u1469\0\u14a0"+
    "\0\u14d7\0\u150e\0\u1469\0\u1545\0\u157c\0\u15b3\0\u15ea";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\3\1\10"+
    "\2\3\1\11\3\3\1\12\2\3\1\13\1\14\1\15"+
    "\1\3\1\16\1\17\2\3\1\20\1\3\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\3\25\2\27\1\30\1\31"+
    "\1\32\1\25\1\33\1\25\1\34\1\25\1\35\1\36"+
    "\1\3\1\37\1\40\1\37\1\2\2\3\70\0\32\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\16\3\1\42\1\3\1\43\11\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\13\3\1\44\16\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\16\3\1\45\13\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\13\3\1\46\12\3\1\47\3\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\1\50\15\3\1\51\13\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\6\3\1\52\5\3\1\53"+
    "\1\54\14\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\23\3\1\55\6\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\4\3\1\56\25\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\22\3\1\57\7\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\10\3\1\60\7\3\1\61\11\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\16\3\1\62\13\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\10\3\1\63\21\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\4\3\1\64"+
    "\25\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\33\0\1\21\67\0\1\22\67\0\1\23\71\0\1\65"+
    "\1\66\72\0\1\25\67\0\1\25\67\0\1\25\70\0"+
    "\1\25\70\0\1\25\70\0\1\25\12\0\32\35\1\0"+
    "\1\67\21\35\1\70\3\35\1\0\1\35\1\0\2\35"+
    "\1\0\32\71\24\0\2\71\1\72\1\0\1\72\1\0"+
    "\2\71\1\0\32\73\10\0\1\74\13\0\1\75\1\73"+
    "\1\37\1\0\1\37\1\0\2\73\63\0\1\76\4\0"+
    "\32\77\10\0\1\100\13\0\2\77\1\41\1\0\1\41"+
    "\1\0\2\77\1\0\16\3\1\101\13\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\4\3\1\102"+
    "\25\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\1\103\31\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\23\3\1\104\6\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\21\3\1\105"+
    "\10\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\22\3\1\106\7\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\13\3\1\107\16\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\2\3\1\0\20\3"+
    "\1\52\11\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\17\3\1\110\12\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\22\3\1\111\7\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\13\3\1\101\16\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\22\3\1\112\7\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\20\3\1\113"+
    "\11\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\11\3\1\114\20\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\23\3\1\115\6\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\2\3\1\0\11\3"+
    "\1\116\20\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\11\3\1\117\20\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\25\3\1\120\4\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\32\65\2\0\25\65\1\0\1\65\1\0\2\65\1\0"+
    "\61\66\1\0\1\66\1\0\2\66\43\0\1\100\15\0"+
    "\1\72\1\0\1\72\4\0\32\73\24\0\3\73\1\0"+
    "\1\73\1\0\2\73\1\0\4\121\2\122\24\121\25\0"+
    "\1\121\1\74\1\0\1\74\1\0\2\121\1\0\32\75"+
    "\24\0\2\75\4\0\2\75\27\0\1\123\36\0\1\123"+
    "\1\0\32\77\24\0\3\77\1\0\1\77\1\0\2\77"+
    "\5\0\2\124\52\0\1\100\1\0\1\100\4\0\13\3"+
    "\1\52\16\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\1\125\31\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\21\3\1\114\10\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\2\3\1\0\1\3"+
    "\1\117\30\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\4\3\1\52\25\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\4\3\1\126\25\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\21\3\1\115\10\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\13\3\1\127\16\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\4\3\1\130"+
    "\25\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\23\3\1\131\6\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\11\3\1\132\20\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\2\3\1\0\21\3"+
    "\1\52\10\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\4\3\1\133\25\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\3\3\1\52\26\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\13\3\1\105\16\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\31\3\1\134\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\32\121\25\0\2\121"+
    "\1\0\1\121\1\0\2\121\1\0\32\121\7\0\1\135"+
    "\15\0\1\121\1\136\1\0\1\136\1\0\2\121\64\0"+
    "\1\137\44\0\1\124\16\0\1\140\1\0\1\140\4\0"+
    "\12\3\1\52\17\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\15\3\1\141\14\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\4\3\1\142"+
    "\25\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\20\3\1\143\11\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\20\3\1\144\11\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\2\3\1\0\15\3"+
    "\1\145\14\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\2\3\1\0\20\3\1\146\11\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\42\0\1\135\16\0\1\136"+
    "\1\0\1\136\4\0\32\121\25\0\1\121\1\136\1\0"+
    "\1\136\1\0\2\121\1\0\7\147\37\0\1\147\11\0"+
    "\1\147\1\0\1\147\1\0\1\147\62\0\1\140\1\0"+
    "\1\140\4\0\3\3\1\114\26\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\2\3\1\0\14\3\1\150\15\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\6\3\1\151\23\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\15\3\1\52\14\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\7\3\1\52"+
    "\22\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\20\3\1\152\11\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\7\153\23\75\14\0\1\147"+
    "\7\0\2\75\1\147\1\0\1\147\1\0\1\153\1\75"+
    "\1\0\4\3\1\154\25\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3\1\0\1\155\31\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\1\156\31\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\2\3\1\0"+
    "\15\3\1\157\14\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\2\3\1\0\2\3\1\105\27\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\2\3\1\0\27\3\1\52"+
    "\2\3\24\0\2\3\1\41\1\0\1\41\1\0\2\3"+
    "\1\0\22\3\1\114\7\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\2\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5665];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\21\1\2\11\41\1\2\11\2\0\3\1"+
    "\1\0\24\1\2\0\10\1\1\0\1\1\1\0\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { lexeme=yytext();return newLine;
          }
        case 16: break;
        case 6: 
          { lexeme=yytext();return SPACE;
          }
        case 17: break;
        case 7: 
          { lexeme=yytext(); return T_Symbol;
          }
        case 18: break;
        case 8: 
          { lexeme=yytext(); return T_EString;
          }
        case 19: break;
        case 1: 
          { lexeme=yytext(); return ERROR;
          }
        case 20: break;
        case 12: 
          { lexeme=yytext(); return T_EComment;
          }
        case 21: break;
        case 2: 
          { lexeme=yytext(); return T_Identifier;
          }
        case 22: break;
        case 14: 
          { lexeme=yytext(); return T_DoubleConstant;
          }
        case 23: break;
        case 9: 
          { lexeme=yytext(); return T_IntConstant;
          }
        case 24: break;
        case 15: 
          { lexeme=yytext(); return T_BoolConstant;
          }
        case 25: break;
        case 11: 
          { lexeme=yytext(); return T_Comment;
          }
        case 26: break;
        case 10: 
          { lexeme=yytext(); return T_Reserved_Word;
          }
        case 27: break;
        case 5: 
          { lexeme=yytext();return TAB;
          }
        case 28: break;
        case 3: 
          { /*Ignore*/
          }
        case 29: break;
        case 13: 
          { lexeme=yytext(); return T_StringConstant;
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
