
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 18 22:01:37 CST 2018
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int sMalloc = 31;
  public static final int sInterface = 18;
  public static final int equality = 38;
  public static final int ClosedCurlyBracket = 15;
  public static final int doubleConstant = 52;
  public static final int cElse = 20;
  public static final int lWhile = 21;
  public static final int denial = 42;
  public static final int DOUBLE = 4;
  public static final int INT = 3;
  public static final int sExtends = 16;
  public static final int comma = 12;
  public static final int stringConstant = 49;
  public static final int OpeningParenthesis = 9;
  public static final int CurlyBrackets = 47;
  public static final int sum = 40;
  public static final int negative = 39;
  public static final int BOOL = 5;
  public static final int sClass = 13;
  public static final int assignment = 26;
  public static final int boolConstant = 51;
  public static final int sReadLine = 36;
  public static final int sReadInteger = 30;
  public static final int ComparisonOperators = 37;
  public static final int EOF = 0;
  public static final int sThis = 27;
  public static final int ident = 50;
  public static final int OpeningCurlyBracket = 14;
  public static final int pyc = 2;
  public static final int error = 1;
  public static final int or = 45;
  public static final int Brackets = 43;
  public static final int sBreak = 24;
  public static final int sNull = 35;
  public static final int sNewArray = 29;
  public static final int cIf = 19;
  public static final int sVoid = 11;
  public static final int sReturn = 23;
  public static final int sGetByte = 33;
  public static final int sSetByte = 34;
  public static final int integerConstant = 48;
  public static final int lFor = 22;
  public static final int and = 44;
  public static final int ArithmeticOperators = 41;
  public static final int sImplements = 17;
  public static final int OpeningBracket = 7;
  public static final int STRING = 6;
  public static final int ClosedBracket = 8;
  public static final int Parenthesis = 46;
  public static final int ClosedParenthesis = 10;
  public static final int sNew = 28;
  public static final int dot = 32;
  public static final int sPrint = 25;
}

