
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 19 11:18:11 CST 2018
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int sMalloc = 32;
  public static final int sInterface = 19;
  public static final int equality = 39;
  public static final int CONST = 3;
  public static final int ClosedCurlyBracket = 16;
  public static final int doubleConstant = 53;
  public static final int cElse = 21;
  public static final int lWhile = 22;
  public static final int denial = 43;
  public static final int DOUBLE = 5;
  public static final int INT = 4;
  public static final int sExtends = 17;
  public static final int comma = 13;
  public static final int stringConstant = 50;
  public static final int OpeningParenthesis = 10;
  public static final int CurlyBrackets = 48;
  public static final int sum = 41;
  public static final int negative = 40;
  public static final int BOOL = 6;
  public static final int sClass = 14;
  public static final int assignment = 27;
  public static final int boolConstant = 52;
  public static final int sReadLine = 37;
  public static final int sReadInteger = 31;
  public static final int ComparisonOperators = 38;
  public static final int EOF = 0;
  public static final int sThis = 28;
  public static final int ident = 51;
  public static final int OpeningCurlyBracket = 15;
  public static final int pyc = 2;
  public static final int error = 1;
  public static final int or = 46;
  public static final int Brackets = 44;
  public static final int sBreak = 25;
  public static final int sNull = 36;
  public static final int sNewArray = 30;
  public static final int cIf = 20;
  public static final int sVoid = 12;
  public static final int sReturn = 24;
  public static final int sGetByte = 34;
  public static final int sSetByte = 35;
  public static final int integerConstant = 49;
  public static final int lFor = 23;
  public static final int and = 45;
  public static final int ArithmeticOperators = 42;
  public static final int sImplements = 18;
  public static final int OpeningBracket = 8;
  public static final int STRING = 7;
  public static final int ClosedBracket = 9;
  public static final int Parenthesis = 47;
  public static final int ClosedParenthesis = 11;
  public static final int sNew = 29;
  public static final int dot = 33;
  public static final int sPrint = 26;
}

