/* The following code was generated by JFlex 1.4.3 on 30/08/18 15:23 */

package analizador;
import static analizador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30/08/18 15:23 from the specification file
 * <tt>C:/Users/TonyTaze/Downloads/Universidad/Sexto Ciclo/COMPILADORES/MiniC-/analizadorLexico/src/analizador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\35\1\34\2\0\1\33\22\0\1\36\1\44\1\56\2\0"+
    "\1\37\1\46\1\0\1\52\1\53\1\41\1\42\1\37\1\42\1\43"+
    "\1\40\1\63\11\61\1\50\1\37\1\44\1\45\1\44\2\0\1\70"+
    "\1\65\1\67\1\65\1\6\1\65\6\60\1\32\1\31\11\60\1\66"+
    "\2\60\1\37\1\0\1\51\1\0\1\57\1\0\1\1\1\2\1\3"+
    "\1\4\1\5\1\7\1\10\1\11\1\12\1\60\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\60\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\60\1\54\1\47\1\55\u1f9e\0\1\62\1\64\udfe2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\16\2\1\3\1\4\1\5\1\6\7\7"+
    "\1\10\1\1\1\11\1\1\12\2\1\12\12\2\1\13"+
    "\1\14\1\10\1\15\2\0\1\1\1\16\1\1\1\0"+
    "\2\2\1\1\10\2\1\12\6\2\1\12\1\14\1\0"+
    "\1\14\2\1\1\0\1\2\1\0\6\2\1\17\1\2"+
    "\1\14\1\0\1\14\1\13\1\0\1\16\1\0\1\2"+
    "\1\1\6\2\1\13\1\11\1\0\3\2\1\1\4\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357"+
    "\0\u0390\0\u03c9\0\u0402\0\71\0\71\0\u043b\0\u0474\0\u04ad"+
    "\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675"+
    "\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d"+
    "\0\u0876\0\162\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc"+
    "\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\71\0\71"+
    "\0\u05ca\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1"+
    "\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79"+
    "\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041"+
    "\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209"+
    "\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\162"+
    "\0\u13d1\0\u140a\0\u1443\0\u147c\0\u147c\0\u14b5\0\u14ee\0\u1527"+
    "\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef"+
    "\0\71\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1728\0\u1845"+
    "\0\u187e\0\u18b7\0\u18f0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\3\1\10"+
    "\2\3\1\11\3\3\1\12\2\3\1\13\1\14\1\15"+
    "\1\3\1\16\1\17\2\3\1\20\1\3\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\3\25\2\27\1\30\1\31"+
    "\1\2\1\25\1\32\1\25\1\33\1\25\1\34\1\35"+
    "\1\3\1\36\1\37\1\36\1\2\2\3\1\40\1\3"+
    "\72\0\32\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\16\3\1\42\1\3\1\43\11\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\13\3"+
    "\1\44\16\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\16\3\1\45\13\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\13\3\1\46\12\3"+
    "\1\47\3\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\1\50\15\3\1\51\13\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\6\3\1\52"+
    "\5\3\1\53\1\54\14\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\23\3\1\55\6\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\4\3"+
    "\1\56\25\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\22\3\1\57\7\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\10\3\1\60\7\3"+
    "\1\61\11\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\16\3\1\62\13\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\10\3\1\63\21\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\4\3\1\64\25\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\33\0\1\21\71\0\1\22\71\0\1\23"+
    "\73\0\1\65\1\66\74\0\1\25\71\0\1\25\71\0"+
    "\1\25\74\0\1\25\72\0\1\25\14\0\32\34\1\0"+
    "\1\67\13\34\1\0\5\34\1\70\3\34\1\0\1\34"+
    "\1\0\4\34\1\0\32\71\24\0\2\71\1\72\1\0"+
    "\1\72\1\0\4\71\1\0\32\73\10\0\1\74\13\0"+
    "\1\75\1\73\1\36\1\0\1\36\1\0\4\73\63\0"+
    "\1\76\6\0\16\3\1\77\13\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\32\100\10\0\1\101"+
    "\13\0\2\100\1\41\1\0\1\41\1\0\4\100\1\0"+
    "\16\3\1\102\13\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\4\3\1\103\25\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\1\104\31\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\23\3\1\105\6\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\21\3\1\106\10\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\22\3\1\107"+
    "\7\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\13\3\1\110\16\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\20\3\1\52\11\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\17\3"+
    "\1\111\12\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\22\3\1\112\7\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\13\3\1\102\16\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\22\3\1\113\7\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\20\3\1\114\11\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\11\3\1\115"+
    "\20\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\23\3\1\116\6\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\11\3\1\117\20\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\11\3"+
    "\1\120\20\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\25\3\1\121\4\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\32\65\2\0\25\65"+
    "\1\0\1\65\1\0\4\65\34\122\1\123\4\122\1\124"+
    "\27\122\43\0\1\101\15\0\1\72\1\0\1\72\6\0"+
    "\32\73\24\0\3\73\1\0\1\73\1\0\4\73\1\0"+
    "\4\125\2\126\24\125\25\0\1\125\1\74\1\0\1\74"+
    "\1\0\4\125\1\0\32\75\24\0\2\75\4\0\4\75"+
    "\27\0\1\127\36\0\1\127\3\0\20\3\1\130\11\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\32\100\24\0\3\100\1\0\1\100\1\0\4\100\5\0"+
    "\2\131\52\0\1\101\1\0\1\101\6\0\13\3\1\52"+
    "\16\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\1\132\31\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\21\3\1\115\10\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\1\3\1\120"+
    "\30\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\4\3\1\52\25\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\4\3\1\133\25\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\21\3"+
    "\1\116\10\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\13\3\1\134\16\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\4\3\1\135\25\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\23\3\1\136\6\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\11\3\1\137\20\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\21\3\1\52"+
    "\10\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\4\3\1\140\25\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\3\3\1\52\26\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\13\3"+
    "\1\106\16\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\31\3\1\141\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\34\122\1\123\4\122\1\142\27\122"+
    "\41\123\1\143\27\123\34\144\1\0\3\144\1\145\1\124"+
    "\27\144\1\0\32\125\25\0\2\125\1\0\1\125\1\0"+
    "\4\125\1\0\32\125\7\0\1\146\15\0\1\125\1\147"+
    "\1\0\1\147\1\0\4\125\64\0\1\150\5\0\32\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\3\3\1\151"+
    "\42\0\1\131\16\0\1\152\1\0\1\152\6\0\12\3"+
    "\1\52\17\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\15\3\1\153\14\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\4\3\1\154\25\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\20\3\1\155\11\3\24\0\2\3\1\41\1\0\1\41"+
    "\1\0\4\3\1\0\20\3\1\156\11\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\15\3\1\157"+
    "\14\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\20\3\1\160\11\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\34\122\1\123\3\122\1\145\1\142"+
    "\27\122\40\123\1\161\1\143\27\123\34\144\1\0\34\144"+
    "\42\0\1\146\16\0\1\147\1\0\1\147\6\0\32\125"+
    "\25\0\1\125\1\147\1\0\1\147\1\0\4\125\1\0"+
    "\7\162\37\0\1\162\11\0\1\162\1\0\1\162\1\0"+
    "\1\162\1\0\2\162\1\0\32\3\22\0\1\163\1\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\61\0\1\152"+
    "\1\0\1\152\6\0\3\3\1\115\26\3\24\0\2\3"+
    "\1\41\1\0\1\41\1\0\4\3\1\0\14\3\1\164"+
    "\15\3\24\0\2\3\1\41\1\0\1\41\1\0\4\3"+
    "\1\0\6\3\1\165\23\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\15\3\1\52\14\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\7\3"+
    "\1\52\22\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\20\3\1\166\11\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\7\167\23\75\14\0"+
    "\1\162\7\0\2\75\1\162\1\0\1\162\1\0\1\167"+
    "\1\75\2\167\51\0\1\25\20\0\4\3\1\170\25\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3\1\0"+
    "\1\171\31\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\1\172\31\3\24\0\2\3\1\41\1\0"+
    "\1\41\1\0\4\3\1\0\15\3\1\173\14\3\24\0"+
    "\2\3\1\41\1\0\1\41\1\0\4\3\1\0\2\3"+
    "\1\106\27\3\24\0\2\3\1\41\1\0\1\41\1\0"+
    "\4\3\1\0\27\3\1\52\2\3\24\0\2\3\1\41"+
    "\1\0\1\41\1\0\4\3\1\0\22\3\1\115\7\3"+
    "\24\0\2\3\1\41\1\0\1\41\1\0\4\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6441];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\21\1\2\11\41\1\2\11\2\0\3\1"+
    "\1\0\24\1\1\0\3\1\1\0\1\1\1\0\11\1"+
    "\1\0\2\1\1\0\1\1\1\0\10\1\1\11\1\1"+
    "\1\0\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { lexeme=yytext();return newLine;
          }
        case 16: break;
        case 6: 
          { lexeme=yytext();return SPACE;
          }
        case 17: break;
        case 7: 
          { lexeme=yytext(); return T_Symbol;
          }
        case 18: break;
        case 8: 
          { lexeme=yytext(); return T_EString;
          }
        case 19: break;
        case 1: 
          { lexeme=yytext(); return ERROR;
          }
        case 20: break;
        case 12: 
          { lexeme=yytext(); return T_EComment;
          }
        case 21: break;
        case 2: 
          { lexeme=yytext(); return T_Identifier;
          }
        case 22: break;
        case 14: 
          { lexeme=yytext(); return T_DoubleConstant;
          }
        case 23: break;
        case 9: 
          { lexeme=yytext(); return T_IntConstant;
          }
        case 24: break;
        case 15: 
          { lexeme=yytext(); return T_BoolConstant;
          }
        case 25: break;
        case 11: 
          { lexeme=yytext(); return T_Comment;
          }
        case 26: break;
        case 10: 
          { lexeme=yytext(); return T_Reserved_Word;
          }
        case 27: break;
        case 5: 
          { lexeme=yytext();return TAB;
          }
        case 28: break;
        case 3: 
          { /*Ignore*/
          }
        case 29: break;
        case 13: 
          { lexeme=yytext(); return T_StringConstant;
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
